
POST http://localhost:8081/author/login
content-type: application/json

{
    "loginId": "jasvin_james",
    "password": "Jasvin@123"
}

###

POST http://localhost:8081/author/login
content-type: application/json

{
    "loginId": "jasvin_james",
    "password": "Jasvin@1"
}

###
GET http://localhost:8081/item?authorId=5

###
GET http://localhost:8081/item?authorId=2

###
GET http://localhost:8081/item?authorId=3

###
POST http://localhost:8081/item
Content-Type: application/json

{
    "author": {
        "loginId": "jasvin_james",
        "password": "Jasvin@123",
        "authorId": 1
    },
    "item": {
        "question": "Dummy question 7?",
        "option1": "Factory Pattern",
        "option2": "Abstract Factory Pattern",
        "option3": "Singleton Pattern",
        "option4": "Transfer Object Pattern",
        "answer": 3
    },
    "itemType": "MCQ",
    "courseId": 1
}

###

POST http://localhost:8081/item
Content-Type: application/json

{
    "author": {
        "loginId": "gaurav_tirodkar",
        "password": "Gaurav@123",
        "authorId": 2
    },
    "item": {
        "question": "Dummy question 6?",
        "answer": false
    },
    "itemType": "TrueFalse",
    "courseId": 1
}

###

POST http://localhost:8081/item
Content-Type: application/json

{
    "author": {
        "loginId": "jasvin_james",
        "password": "Jasvin@123",
        "authorId": 1
    },
    "item": {
        "question": "Dummy question 4?",
        "answer": false
    },
    "itemType": "TrueFalse",
    "courseId": 1
}



###

PUT http://localhost:8081/item/6
Content-Type: application/json

{
    "author": {
        "loginId": "gaurav_tirodkar",
        "password": "Gaurav@123",
        "authorId": 2
    },
    "item": {
        "itemId": 6,
        "question": "Dummy TF 69?"
    },
    "itemType": "TrueFalse",
}